#!/usr/bin/env node
/**
 * Copies the browser-safe parts of packages/core/src into packages/web/src/vendor/ans-core,
 * and the public docs the web renders into packages/web/src/content.
 *
 * Why a copy: the Vercel project builds packages/web on its own, so the web app cannot
 * depend on a pnpm workspace package. The copy is byte-identical and checked:
 *   node scripts/sync-core.mjs          write the copies
 *   node scripts/sync-core.mjs --check  exit 1 when any copy differs from its source
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const web = resolve(here, '..');
const repo = resolve(web, '..', '..');

const CORE_FILES = ['crypto.ts', 'canonical.ts', 'signing.ts', 'receipts.ts', 'money.ts', 'errors.ts', 'apikeys.ts', 'wire.ts'];
const DOC_FILES = [
  ['docs/TRUST.md', 'src/content/trust.md'],
  ['docs/MONEY.md', 'src/content/money.md'],
];

const INDEX = `// Generated by scripts/sync-core.mjs from packages/core/src. Do not edit these files by hand;
// edit packages/core/src and run: node scripts/sync-core.mjs
${CORE_FILES.map((f) => `export * from './${f.replace(/\.ts$/, '')}';`).join('\n')}
`;

const pairs = [
  ...CORE_FILES.map((f) => [join(repo, 'packages/core/src', f), join(web, 'src/vendor/ans-core', f)]),
  ...DOC_FILES.map(([from, to]) => [join(repo, from), join(web, to)]),
];

const check = process.argv.includes('--check');
let drift = 0;

for (const [from, to] of pairs) {
  if (!existsSync(from)) {
    console.error(`missing source: ${from}`);
    drift++;
    continue;
  }
  const source = readFileSync(from, 'utf8');
  if (check) {
    const copy = existsSync(to) ? readFileSync(to, 'utf8') : null;
    if (copy !== source) {
      console.error(`out of sync: ${to}`);
      drift++;
    }
  } else {
    mkdirSync(dirname(to), { recursive: true });
    writeFileSync(to, source);
  }
}

const indexPath = join(web, 'src/vendor/ans-core/index.ts');
if (check) {
  const current = existsSync(indexPath) ? readFileSync(indexPath, 'utf8') : null;
  if (current !== INDEX) {
    console.error(`out of sync: ${indexPath}`);
    drift++;
  }
} else {
  writeFileSync(indexPath, INDEX);
}

if (check && drift > 0) {
  console.error(`${drift} file(s) out of sync; run: node packages/web/scripts/sync-core.mjs`);
  process.exit(1);
}
console.log(check ? 'vendor copies are in sync' : `synced ${pairs.length + 1} files`);
